import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const mainJsPath = path.resolve(__dirname, '../dist-electron/main.js');

console.log('[Smoke Test] Verifying build artifact:', mainJsPath);

if (!fs.existsSync(mainJsPath)) {
  console.error('[Smoke Test Fail] dist-electron/main.js does not exist. Run build first.');
  process.exit(1);
}

const code = fs.readFileSync(mainJsPath, 'utf-8');

// 1. Check for unhandled CJS/ESM require fallback error generated by bundler
if (code.includes('Calling `require` for') || code.includes("doesn't expose the `require` function")) {
  console.error('[Smoke Test Fail] Found CJS/ESM require mismatch error pattern in dist-electron/main.js!');
  process.exit(1);
}

// 2. Validate JavaScript syntax
try {
  new vm.Script(code, { filename: 'main.js' });
  console.log('[Smoke Test Pass] dist-electron/main.js syntax and bundle verification passed successfully.');
} catch (err) {
  console.error('[Smoke Test Fail] Syntax or parse error in dist-electron/main.js:', err);
  process.exit(1);
}
